apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service-proxy
  labels:
    app.kubernetes.io/name: sample-service-proxy
    app.kubernetes.io/instance: sample-service-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-service-proxy
      app.kubernetes.io/instance: sample-service-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-service-proxy
        app.kubernetes.io/instance: sample-service-proxy
    spec:
      containers:
        - name: sample-service-proxy
          env:
            - name: BIND_ADDRESS
              value: 0.0.0.0:8080
            - name: METRICS_BIND_ADDRESS
              value: 0.0.0.0:8081
            - name: UPSTREAM_HOST
              value: sample-service.default.svc.cluster.local
            - name: UPSTREAM_SCHEME
              value: http
            - name: AUTH_PROVIDER
              value: key
            - name: AUTH_TOKEN_HEADER
              value: "Authorization"
            - name: AUTH_PRE_SHARED_KEY
              value: "0123456789"
          image: "europe-north1-docker.pkg.dev/nais-io/nais/images/authproxy:sha-155a58e"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi

