name: Build and push
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/workflows/pr.yaml"
      - ".github/workflows/dependabot-auto-merge.yaml"
permissions:
  contents: read
env:
  REGISTRY: europe-north1-docker.pkg.dev/nais-io/nais/images
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6
      - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # ratchet:jdx/mise-action@v4
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # ratchet:actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - run: mise run check
      - run: mise run test
  build_and_push:
    if: github.ref == 'refs/heads/main'
    needs: [tests]
    permissions:
      id-token: "write"
      packages: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6
      - name: Install cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # ratchet:sigstore/cosign-installer@v4.1.2
        with:
          cosign-release: 'v3.0.2'
      - name: Verify runner image
        run: cosign verify --certificate-oidc-issuer https://accounts.google.com  --certificate-identity keyless@distroless.iam.gserviceaccount.com gcr.io/distroless/static-debian12:nonroot
      - uses: nais/platform-build-push-sign@31014e4bcac554cb52525fe2364244c5166b84d2 # ratchet:nais/platform-build-push-sign@main
        id: build_push_sign
        with:
          name: authproxy
          dockerfile: Dockerfile
          google_service_account: gh-authproxy
          push: true
          push_ghcr: true
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
