name: PR Check
on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE.md'
permissions:
  contents: read
jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6
      - uses: jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # ratchet:jdx/mise-action@v4
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # ratchet:actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - run: mise run check
      - run: mise run test
