name: PR Check
on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE.md'
permissions:
  contents: read
jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # ratchet:jdx/mise-action@v3
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # ratchet:actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - run: mise run check
      - run: mise run test
